### ISSUE TITLE
MessageJob creation should not cause error on not-acknowledged Dinner

### ISSUE THREAD

**Issue by Clemens85** [Clemens85/runningdinner#13]
See stacktrace:

```
org.runningdinner.common.exception.DinnerNotAcknowledgedException: Failed to create MessageJob{TEAM_PARTNER_WISH, 1, XXX, XXX} due to dinner XXX is not yet acknowledged
	at org.runningdinner.admin.message.MessageService.checkAcknowledgedDinner(MessageService.java:713)
	at org.runningdinner.admin.message.MessageService.executeSendMessagesJobAfterCommit(MessageService.java:693)
	at org.runningdinner.admin.message.MessageService.sendTeamPartnerWishMail(MessageService.java:310)
	at org.runningdinner.admin.message.MessageService$$FastClassBySpringCGLIB$$a80b063b.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:769)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:366)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:99)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)
	at org.runningdinner.admin.message.MessageService$$EnhancerBySpringCGLIB$$9bacc399.sendTeamPartnerWishMail(<generated>)
	at org.runningdinner.participant.partnerwish.TeamPartnerWishStateHandlerService.sendTeamPartnerInvitationMessage(TeamPartnerWishStateHandlerService.java:89)
	at org.runningdinner.participant.partnerwish.TeamPartnerWishStateHandlerService.handleTeamPartnerWishForSubscribedParticipant(TeamPartnerWishStateHandlerService.java:66)
	at org.runningdinner.participant.ParticipantService.updateParticipantSubscription(ParticipantService.java:258)
	at org.runningdinner.participant.ParticipantService$$FastClassBySpringCGLIB$$c3224024.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:769)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:366)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:99)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)
	at org.runningdinner.participant.ParticipantService$$EnhancerBySpringCGLIB$$8d4d6af4.updateParticipantSubscription(<generated>)
	at org.runningdinner.participant.rest.ParticipantServiceRest.activateParticipantSubscription(ParticipantServiceRest.java:108)
	at sun.reflect.GeneratedMethodAccessor1172.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:888)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:793)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) 
```

**Comment by Clemens85** [comment]
- Admin area: Provide functionality for forcing user into acknowledging the dinner (Provide the means for re-sending the link and optionally an text input for re-entering the current admin email). Provide also a possibility to contact global admin if it is just not working
- Show this into notification area as an action link to trigger a modal dialog.
- Change notification into more dangerous color
- Team partner wish invitation emails and also participant registration emails shall just work, also when dinner is not acknowledged yet
- (If at least one registration was however performed with not acknowledged dinner, the modal dialog shall even immediately be opened in admin area in dashboard => Not implemented in first step)
