### ISSUE TITLE
Error in backend task for checknig suppresed mails

### ISSUE THREAD

**Issue by Clemens85** [Clemens85/runningdinner#9]
Stacktrace:

```
org.runningdinner.common.exception.TechnicalException: org.runningdinner.common.exception.TechnicalException: java.io.IOException: Request returned status Code 500Body:{"errors":[{"field":null,"message":"internal server error"}]}
	at org.runningdinner.mail.sendgrid.SendGridEmailSynchronizationSchedulerService.synchronizeSentMails(SendGridEmailSynchronizationSchedulerService.java:56)
	at org.runningdinner.mail.sendgrid.SendGridEmailSynchronizationSchedulerService.triggerSynchronizationOfSentMails(SendGridEmailSynchronizationSchedulerService.java:37)
	at sun.reflect.GeneratedMethodAccessor168.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at net.javacrumbs.shedlock.core.DefaultLockingTaskExecutor.executeWithLock(DefaultLockingTaskExecutor.java:54)
	at net.javacrumbs.shedlock.core.DefaultLockingTaskExecutor.executeWithLock(DefaultLockingTaskExecutor.java:39)
	at net.javacrumbs.shedlock.core.DefaultLockManager.executeWithLock(DefaultLockManager.java:51)
	at net.javacrumbs.shedlock.core.LockableRunnable.run(LockableRunnable.java:35)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.runningdinner.common.exception.TechnicalException: java.io.IOException: Request returned status Code 500Body:{"errors":[{"field":null,"message":"internal server error"}]}
	at org.runningdinner.mail.sendgrid.SendGridMailWrapper.findSuppressedEmails(SendGridMailWrapper.java:146)
	at org.runningdinner.mail.sendgrid.SendGridMailWrapper.findInvalidMails(SendGridMailWrapper.java:93)
	at org.runningdinner.mail.sendgrid.SendGridEmailSynchronizationService.synchronizeInvalidEmails(SendGridEmailSynchronizationService.java:124)
	at org.runningdinner.mail.sendgrid.SendGridEmailSynchronizationService.synchronizeSuppressedEmails(SendGridEmailSynchronizationService.java:62)
	at org.runningdinner.mail.sendgrid.SendGridEmailSynchronizationService$$FastClassBySpringCGLIB$$5065e1f3.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:685)
	at org.runningdinner.mail.sendgrid.SendGridEmailSynchronizationService$$EnhancerBySpringCGLIB$$230d73df.synchronizeSuppressedEmails(<generated>)
	at org.runningdinner.mail.sendgrid.SendGridEmailSynchronizationSchedulerService.synchronizeSentMails(SendGridEmailSynchronizationSchedulerService.java:51)
	... 17 common frames omitted
Caused by: java.io.IOException: Request returned status Code 500Body:{"errors":[{"field":null,"message":"internal server error"}]}
	at com.sendgrid.Client.executeApiCall(Client.java:288)
	at com.sendgrid.Client.get(Client.java:162)
	at com.sendgrid.Client.api(Client.java:309)
	at com.sendgrid.SendGrid.makeCall(SendGrid.java:96)
	at com.sendgrid.SendGrid.api(SendGrid.java:115)
	at org.runningdinner.mail.sendgrid.SendGridMailWrapper.findSuppressedEmails(SendGridMailWrapper.java:142)
	... 25 common frames omitted
```

**Comment by Clemens85** [comment]
Seems to be no bug in app, but bug in SendGrid backend server that occured once (and not any longer)
